//! Command-line parsing, exercised through the public `parse` entry point.
//!
//! Every flag here is generated by `modules/edge.nix` or `modules/proxy.nix`,
//! so a bad value means a bad NixOS option — and the point of rejecting it at
//! parse time is that the failure names the flag, at boot, instead of
//! surfacing later as "port range exhausted" for a range that was never
//! usable or as a reconciler spinning on a zero-length interval.

use losos_registrar::opts::{parse, Mode};

/// Flags every `serve` invocation needs. Overrides are *prepended* by
/// [`serve_args`], and the parser takes the first occurrence of a flag, so an
/// override wins over the default below.
const SERVE_DEFAULTS: &[&str] = &[
    "--registry",
    "/var/lib/losos-registrar/registry.json",
    "--traefik-dir",
    "/etc/traefik/dynamic",
    "--rathole-config",
    "/etc/rathole/server.toml",
    "--bootstrap-token-file",
    "/var/secrets/bootstrap",
    "--tenants-file",
    "/nix/store/tenants.json",
    "--port-range",
    "50000-50100",
];

fn serve_args(overrides: &[&str]) -> Vec<String> {
    std::iter::once("serve")
        .chain(overrides.iter().copied())
        .chain(SERVE_DEFAULTS.iter().copied())
        .map(str::to_string)
        .collect()
}

/// Flags every `join` invocation needs, with the same prepend-to-override
/// trick [`serve_args`] uses.
const JOIN_DEFAULTS: &[&str] = &[
    "--registrar-url",
    "https://register.losos.cfd",
    "--appliance-id",
    "mattbox-01",
    "--node-name",
    "mattbox-01",
    "--token-file",
    "/var/secrets/losos-proxy-token",
    "--out-token-file",
    "/var/secrets/losos-mesh-token",
];

fn join_args(overrides: &[&str]) -> Vec<String> {
    std::iter::once("join")
        .chain(overrides.iter().copied())
        .chain(JOIN_DEFAULTS.iter().copied())
        .map(str::to_string)
        .collect()
}

fn serve_opts(overrides: &[&str]) -> losos_registrar::opts::ServeOpts {
    match parse(serve_args(overrides)) {
        Ok(Mode::Serve(opts)) => opts,
        Ok(_) => panic!("expected a serve mode"),
        Err(e) => panic!("expected serve args to parse: {e:?}"),
    }
}

#[test]
fn a_full_serve_invocation_parses() {
    let opts = serve_opts(&[]);
    assert_eq!(opts.port_range, (50000, 50100));
    assert_eq!(opts.listen, "127.0.0.1:8443");
    assert_eq!(opts.reconcile_interval, std::time::Duration::from_secs(15));
    assert_eq!(opts.heartbeat_ttl, std::time::Duration::from_secs(120));
}

/// An inverted range makes `alloc_port`'s `(lo..=hi)` sweep empty, so the
/// first appliance to register would be told the range is exhausted with no
/// hint that the range itself was the problem.
#[test]
fn an_inverted_port_range_is_rejected() {
    let result = parse(serve_args(&["--port-range", "50100-50000"]));
    assert!(result.is_err(), "hi < lo must not parse");
}

#[test]
fn a_port_range_starting_at_zero_is_rejected() {
    let result = parse(serve_args(&["--port-range", "0-50100"]));
    assert!(result.is_err(), "port 0 is not bindable");
}

#[test]
fn a_malformed_port_range_is_rejected() {
    for range in ["50000", "50000-", "-50100", "fifty-thousand", ""] {
        let result = parse(serve_args(&["--port-range", range]));
        assert!(result.is_err(), "{range:?} must not parse as a range");
    }
}

#[test]
fn an_equal_low_and_high_range_is_a_single_usable_port() {
    let opts = serve_opts(&["--port-range", "50000-50000"]);
    assert_eq!(opts.port_range, (50000, 50000));
}

/// Zero is never a sane value for any duration this crate parses: a zero
/// reconcile interval is a busy-loop, a zero TTL prunes every tenant on the
/// next tick, and a zero heartbeat interval floods the edge.
#[test]
fn a_zero_duration_is_rejected() {
    for flag in ["--reconcile-interval", "--heartbeat-ttl"] {
        for value in ["0", "0s", "0ms", "0m", "0h"] {
            let result = parse(serve_args(&[flag, value]));
            assert!(result.is_err(), "{flag} {value} must not parse");
        }
    }
}

/// `n * 3600` used to overflow `u64` seconds unchecked — a panic in a debug
/// build, and a silently tiny interval in a release one.
#[test]
fn an_overflowing_duration_is_rejected_not_wrapped() {
    for value in [
        "5124095576030432h",
        "18446744073709551615h",
        "999999999999999999m",
    ] {
        let result = parse(serve_args(&["--heartbeat-ttl", value]));
        assert!(result.is_err(), "{value} must be rejected, not wrapped");
    }
}

#[test]
fn duration_units_are_honoured() {
    use std::time::Duration;
    let cases = [
        ("500ms", Duration::from_millis(500)),
        ("30s", Duration::from_secs(30)),
        ("2m", Duration::from_secs(120)),
        ("1h", Duration::from_secs(3600)),
        ("45", Duration::from_secs(45)),
    ];
    for (text, expected) in cases {
        let opts = serve_opts(&["--heartbeat-ttl", text]);
        assert_eq!(opts.heartbeat_ttl, expected, "parsing {text:?}");
    }
}

#[test]
fn a_missing_required_flag_is_rejected() {
    // No --registry anywhere in the argument list.
    let args: Vec<String> = ["serve", "--port-range", "50000-50100"]
        .into_iter()
        .map(str::to_string)
        .collect();
    assert!(parse(args).is_err());
}

/// The mesh flags are all optional, and an edge that omits them parses exactly
/// the argument list it always did — which is what keeps
/// `losos.edge.cluster.enable = false` a no-op on the master-proxy half.
#[test]
fn serve_without_the_mesh_flags_leaves_the_join_route_unconfigured() {
    let opts = serve_opts(&[]);
    assert!(opts.mesh_agent_token_file.is_none());
    assert!(opts.mesh_server_addr.is_none());
    assert!(opts.kube_token_file.is_none());
    assert!(opts.kube_ca_file.is_none());
    assert_eq!(opts.kube_api, "https://127.0.0.1:6443");
    assert_eq!(
        opts.compute_windows_file,
        "/var/lib/losos-registrar/compute-windows.json"
    );
}

#[test]
fn serve_parses_the_mesh_flags() {
    let opts = serve_opts(&[
        "--mesh-agent-token-file",
        "/var/secrets/losos-mesh-agent-token",
        "--mesh-server-addr",
        "https://198.51.100.7:9345",
        "--kube-api",
        "https://127.0.0.1:6443/",
        "--kube-token-file",
        "/var/secrets/losos-mesh-kube-token",
        "--kube-ca-file",
        "/var/secrets/losos-mesh-kube-ca.crt",
        "--compute-windows-file",
        "/var/lib/losos-registrar/compute-windows.json",
    ]);
    assert_eq!(
        opts.mesh_agent_token_file.as_deref(),
        Some("/var/secrets/losos-mesh-agent-token")
    );
    assert_eq!(
        opts.mesh_server_addr.as_deref(),
        Some("https://198.51.100.7:9345")
    );
    // The trailing slash is stripped at parse time; the cleanup builds URLs by
    // concatenating "/api/v1/...", and "…:6443//api/v1/nodes/x" is a 404 from
    // the apiserver that would read as "nothing to clean up".
    assert_eq!(opts.kube_api, "https://127.0.0.1:6443");
}

/// `--share-compute` is interpolated straight out of a Nix bool, so anything
/// other than `true`/`false` means the module emitted something it did not
/// intend — a boot-time failure naming the flag beats a silent `false` that
/// quietly stops the box contributing compute.
#[test]
fn join_rejects_a_non_boolean_share_compute() {
    for value in ["yes", "1", "True", ""] {
        assert!(
            parse(join_args(&["--share-compute", value])).is_err(),
            "--share-compute {value:?} must not parse"
        );
    }
    assert!(parse(join_args(&["--share-compute", "true"])).is_ok());
}

/// The same `HH:MM` rule lososd and the edge enforce, checked here so a bad
/// window fails at boot with the flag named rather than travelling to the edge
/// to come back as an opaque 400 on a box with no shell.
#[test]
fn join_rejects_a_window_that_is_not_hhmm() {
    for value in ["24:00", "7:00", "23:60", "23:5", "", "1:2:3", "07:00:00"] {
        assert!(
            parse(join_args(&["--window-start", value])).is_err(),
            "--window-start {value:?} must not parse"
        );
        assert!(
            parse(join_args(&["--window-end", value])).is_err(),
            "--window-end {value:?} must not parse"
        );
    }
    for value in ["00:00", "07:00", "23:59"] {
        assert!(
            parse(join_args(&["--window-start", value])).is_ok(),
            "--window-start {value:?} must parse"
        );
    }
}

#[test]
fn join_parses_its_own_flags() {
    match parse(join_args(&[
        "--share-compute",
        "true",
        "--expect-server-addr",
        "https://edge.losos.cfd:9345",
    ])) {
        Ok(Mode::Join(opts)) => {
            assert_eq!(opts.appliance_id, "mattbox-01");
            assert_eq!(opts.node_name, "mattbox-01");
            assert!(opts.share_compute);
            assert_eq!(opts.window_start, "23:00");
            assert_eq!(opts.window_end, "07:00");
            assert_eq!(
                opts.expect_server_addr.as_deref(),
                Some("https://edge.losos.cfd:9345")
            );
        }
        other => panic!("expected a join mode, got {}", mode_name(&other)),
    }
}

/// Sharing off is the default, so an `ExecStart` that omitted the flag
/// entirely cannot accidentally opt an owner into running other people's pods.
#[test]
fn join_defaults_to_not_sharing_compute() {
    match parse(join_args(&[])) {
        Ok(Mode::Join(opts)) => assert!(!opts.share_compute),
        other => panic!("expected a join mode, got {}", mode_name(&other)),
    }
}

#[test]
fn an_unknown_subcommand_is_rejected() {
    assert!(parse(vec!["frobnicate".to_string()]).is_err());
    assert!(parse(Vec::new()).is_err());
}

#[test]
fn announce_parses_its_own_flags() {
    let args: Vec<String> = [
        "announce",
        "--registrar-url",
        "https://register.losos.cfd",
        "--appliance-id",
        "mattbox",
        "--hostname",
        "mattbox.losos.cfd",
        "--token-file",
        "/var/secrets/losos-proxy-token",
        "--heartbeat-interval",
        "30s",
    ]
    .into_iter()
    .map(str::to_string)
    .collect();
    match parse(args) {
        Ok(Mode::Announce(opts)) => {
            assert_eq!(opts.appliance_id, "mattbox");
            assert_eq!(opts.heartbeat_interval, std::time::Duration::from_secs(30));
        }
        other => panic!("expected an announce mode, got {}", mode_name(&other)),
    }
}

#[test]
fn identity_verify_takes_the_four_facts_the_box_checks() {
    use losos_registrar::opts::IdentityOpts;
    let args: Vec<String> = [
        "identity",
        "verify",
        "--root-public",
        "ab",
        "--url",
        "https://e.example",
        "--nonce",
        "0011",
        "--answer",
        "-",
    ]
    .iter()
    .map(|s| s.to_string())
    .collect();
    match parse(args) {
        Ok(Mode::Identity(IdentityOpts::Verify {
            root_public,
            url,
            nonce,
            answer,
        })) => {
            assert_eq!(root_public, "ab");
            assert_eq!(url, "https://e.example");
            assert_eq!(nonce, "0011");
            assert_eq!(answer, "-");
        }
        other => panic!("expected identity verify, got {}", mode_name(&other)),
    }
    let missing: Vec<String> = ["identity", "verify", "--url", "https://e.example"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert!(
        parse(missing).is_err(),
        "verify without the root key parsed"
    );
}

fn mode_name(mode: &miette::Result<Mode>) -> &'static str {
    match mode {
        Ok(Mode::Serve(_)) => "serve",
        Ok(Mode::Announce(_)) => "announce",
        Ok(Mode::Seed(_)) => "seed",
        Ok(Mode::Join(_)) => "join",
        Ok(Mode::StripeGate(_)) => "stripe-gate",
        Ok(Mode::Identity(_)) => "identity",
        Ok(Mode::Provision(_)) => "provision",
        Ok(Mode::Enrol(_)) => "enrol",
        Ok(Mode::Lab(_)) => "lab",
        Ok(Mode::BuilderSetup(_)) => "builder-setup",
        Err(_) => "error",
    }
}

const MARKET_FLAGS: &[&str] = &[
    "--market-gate-socket",
    "/run/losos-stripe-gate/gate.sock",
    "--market-return-url",
    "https://losos.cfd/market",
];

#[test]
fn the_market_is_off_unless_a_gate_socket_is_given() {
    assert!(serve_opts(&[]).market.is_none());
}

#[test]
fn a_market_serve_invocation_takes_a_four_percent_cut_by_default() {
    let opts = serve_opts(MARKET_FLAGS);
    let market = opts.market.expect("market enabled");
    assert_eq!(market.fee_bps, 400);
    assert_eq!(market.currency, "eur");
    assert_eq!(market.gate_socket, "/run/losos-stripe-gate/gate.sock");
    assert_eq!(market.state_file, "/var/lib/losos-registrar/market.json");
    assert_eq!(market.storage_class, "longhorn");
}

#[test]
fn market_flags_are_all_or_nothing_and_bounded() {
    // Taking payment without a place to send the buyer back to must fail at
    // boot.
    let missing = "--market-return-url";
    let args: Vec<&str> = MARKET_FLAGS
        .chunks(2)
        .filter(|pair| pair[0] != missing)
        .flatten()
        .copied()
        .collect();
    assert!(parse(serve_args(&args)).is_err(), "{missing} is required");
    for (flag, bad) in [
        ("--market-fee-bps", "2001"),
        ("--market-fee-bps", "four"),
        ("--market-currency", "EUR"),
        ("--market-currency", "euro"),
        ("--market-currency", "jpy"),
        ("--market-currency", "kwd"),
        ("--market-return-url", "ftp://x"),
        ("--market-storage-class", ""),
        ("--market-storage-class", "Longhorn"),
        ("--market-storage-class", "a..b"),
        ("--market-storage-class", "a.-b"),
        ("--market-storage-class", "-a"),
        ("--market-storage-class", "a_b"),
        ("--market-storage-class", &"a".repeat(64)),
        ("--market-storage-class", &format!("{}.b", "a".repeat(64))),
        ("--market-storage-class", &vec!["a".repeat(63); 4].join(".")),
    ] {
        let mut args = vec![flag, bad];
        args.extend(MARKET_FLAGS);
        assert!(parse(serve_args(&args)).is_err(), "{flag} {bad}");
    }
    let mut args = vec!["--market-fee-bps", "250", "--market-currency", "usd"];
    args.extend(MARKET_FLAGS);
    let market = serve_opts(&args).market.expect("market enabled");
    assert_eq!((market.fee_bps, market.currency.as_str()), (250, "usd"));
    // 63 + 1 + 63 + 1 + 63 + 1 + 61: every label at its limit, 253 in all.
    let longest = format!(
        "{}.{}.{}.{}",
        "a".repeat(63),
        "b".repeat(63),
        "c".repeat(63),
        "d".repeat(61)
    );
    for good in ["longhorn-ssd", "longhorn.io.v2", longest.as_str()] {
        let mut args = vec!["--market-storage-class", good];
        args.extend(MARKET_FLAGS);
        let market = serve_opts(&args).market.expect("market enabled");
        assert_eq!(market.storage_class, good);
    }
}

#[test]
fn the_stripe_gate_subcommand_parses_and_validates() {
    let args = |extra: &[&str]| -> Vec<String> {
        ["stripe-gate", "--socket", "/run/g.sock"]
            .into_iter()
            .chain(extra.iter().copied())
            .map(String::from)
            .collect()
    };
    let full = [
        "--stripe-key-file",
        "/run/credentials/g/key",
        "--webhook-secret-file",
        "/run/credentials/g/hook",
        "--currency",
        "eur",
    ];
    match parse(args(&full)) {
        Ok(Mode::StripeGate(gate)) => {
            assert_eq!(gate.socket, "/run/g.sock");
            assert_eq!(gate.currency, "eur");
            assert_eq!(gate.stripe_api, "https://api.stripe.com");
        }
        other => panic!("expected stripe-gate, got {}", mode_name(&other)),
    }
    assert!(parse(args(&["--currency", "EUR"])).is_err());
    assert!(parse(args(&[])).is_err(), "the key file is required");
}

/// Federation flags: absent, an edge neither enrols nor relays — the shape
/// every internet-facing edge keeps; present, the uplink reads its hub from
/// a file and the client config path and cadence have defaults.
#[test]
fn federation_flags_are_off_unless_given() {
    let opts = serve_opts(&[]);
    assert!(opts.enrol_dir.is_none());
    assert!(opts.uplink.is_none());

    let opts = serve_opts(&[
        "--enrol-dir",
        "/var/lib/losos-registrar/enrolled",
        "--uplink-file",
        "/var/lib/losos-edge/uplink.json",
    ]);
    assert_eq!(
        opts.enrol_dir.as_deref(),
        Some("/var/lib/losos-registrar/enrolled")
    );
    let uplink = opts.uplink.expect("uplink on");
    assert_eq!(uplink.file, "/var/lib/losos-edge/uplink.json");
    assert_eq!(uplink.rathole_config, "/etc/rathole/uplink.toml");
    assert_eq!(uplink.interval, std::time::Duration::from_secs(30));

    let opts = serve_opts(&[
        "--uplink-file",
        "u.json",
        "--uplink-rathole-config",
        "/tmp/up.toml",
        "--uplink-interval",
        "5s",
    ]);
    let uplink = opts.uplink.expect("uplink on");
    assert_eq!(uplink.rathole_config, "/tmp/up.toml");
    assert_eq!(uplink.interval, std::time::Duration::from_secs(5));
}

#[test]
fn enrol_takes_a_dir_and_forget_one_positional_id() {
    use losos_registrar::opts::EnrolOpts;
    let args = |a: &[&str]| a.iter().map(|s| s.to_string()).collect::<Vec<_>>();
    let enrol = |a: &[&str]| match parse(args(a)) {
        Ok(Mode::Enrol(e)) => Some(e),
        _ => None,
    };
    assert_eq!(
        enrol(&["enrol", "list", "--dir", "/var/lib/x"]),
        Some(EnrolOpts::List {
            dir: "/var/lib/x".into()
        })
    );
    for order in [
        &["enrol", "forget", "--dir", "/var/lib/x", "mattbox"][..],
        &["enrol", "forget", "mattbox", "--dir", "/var/lib/x"][..],
    ] {
        assert_eq!(
            enrol(order),
            Some(EnrolOpts::Forget {
                dir: "/var/lib/x".into(),
                id: "mattbox".into()
            })
        );
    }
    assert_eq!(
        mode_name(&parse(args(&["enrol", "forget", "--dir", "/x"]))),
        "error"
    );
    assert_eq!(mode_name(&parse(args(&["enrol", "list"]))), "error");
}

fn lab(flags: &[&str]) -> miette::Result<losos_registrar::lab::LabOpts> {
    let args: Vec<String> = std::iter::once("lab")
        .chain(flags.iter().copied())
        .map(str::to_string)
        .collect();
    match parse(args) {
        Ok(Mode::Lab(o)) => Ok(o),
        Ok(other) => panic!("expected lab, got {}", mode_name(&Ok(other))),
        Err(e) => Err(e),
    }
}

#[test]
fn lab_with_no_flags_listens_on_loopback_and_uses_the_session_uri() {
    let o = lab(&[]).expect("parses");
    assert_eq!(o.listen, "127.0.0.1:8095");
    assert_eq!(o.connect, "qemu:///session");
    assert_eq!(o.max_guests, 8);
    assert_eq!(o.memory_mib, 96);
    assert_eq!(o.virt_type, losos_registrar::lab::VirtType::Auto);
    assert!(o.origins.iter().any(|x| x == "http://localhost:8080"));
}

#[test]
fn lab_takes_several_origins_and_refuses_paths_in_them() {
    let o = lab(&[
        "--origin",
        "https://lab.example.org/",
        "--origin",
        "http://mattbox.local",
        "--connect",
        "qemu:///system",
        "--virt-type",
        "qemu",
    ])
    .expect("parses");
    assert!(o.origins.iter().any(|x| x == "https://lab.example.org"));
    assert!(o.origins.iter().any(|x| x == "http://mattbox.local"));
    assert_eq!(o.connect, "qemu:///system");
    for bad in ["lab.example.org", "https://a/b", "ftp://a", "https://"] {
        assert!(lab(&["--origin", bad]).is_err(), "{bad}");
    }
}

#[test]
fn lab_bounds_its_numbers_and_its_uri() {
    assert!(lab(&["--max-guests", "0"]).is_err());
    assert!(lab(&["--max-guests", "65"]).is_err());
    assert!(lab(&["--memory", "16"]).is_err());
    assert!(lab(&["--memory", "128"]).is_ok());
    assert!(lab(&["--virt-type", "xen"]).is_err());
    assert!(lab(&["--connect", "xen:///system"]).is_err());
    assert!(lab(&["--idle", "0"]).is_err());
}

const BUILDER_FLAGS: &[&str] = &[
    "--builder-key-file",
    "/run/credentials/losos-registrar.service/claude-api-key",
    "--builder-agent-id",
    "agent_011abc",
    "--builder-environment-id",
    "env_011abc",
];

fn with_market(extra: &[&'static str]) -> Vec<&'static str> {
    MARKET_FLAGS.iter().chain(extra).copied().collect()
}

#[test]
fn the_builder_is_off_unless_a_key_file_is_given_and_marks_up_twenty_percent() {
    assert!(serve_opts(MARKET_FLAGS).builder.is_none());
    let b = serve_opts(&with_market(BUILDER_FLAGS))
        .builder
        .expect("builder enabled");
    assert_eq!(b.markup_bps, 2_000);
    assert_eq!(b.usd_rate_ppm, 1_000_000);
    assert_eq!(b.packs, vec![500, 1_000, 2_000]);
    assert_eq!(b.max_build_cents, 300);
    assert_eq!(b.api, "https://api.anthropic.com");
    assert_eq!(b.state_file, "/var/lib/losos-registrar/builder.json");
}

#[test]
fn builder_flags_are_checked() {
    // No market, no builder: top-ups go through the market's gate.
    assert!(parse(serve_args(BUILDER_FLAGS)).is_err());
    let rate = |r: &'static str| {
        let mut a = with_market(BUILDER_FLAGS);
        a.extend(["--builder-usd-rate", r]);
        parse(serve_args(&a)).map(|m| match m {
            Mode::Serve(o) => o.builder.unwrap().usd_rate_ppm,
            _ => 0,
        })
    };
    assert_eq!(rate("0.92").unwrap(), 920_000);
    assert_eq!(rate("1").unwrap(), 1_000_000);
    assert_eq!(rate("25.5").unwrap(), 25_500_000);
    for bad in ["0", "-1", "0.0000001", "1e3", "abc", ".5", "1,2"] {
        assert!(rate(bad).is_err(), "{bad}");
    }
    let one = |flag: &'static str, v: &'static str| {
        let mut a = with_market(BUILDER_FLAGS);
        a.extend([flag, v]);
        parse(serve_args(&a))
    };
    assert!(one("--builder-markup-bps", "10001").is_err());
    assert!(one("--builder-markup-bps", "0").is_ok());
    assert!(one("--builder-packs", "500,99").is_err());
    assert!(one("--builder-packs", "").is_err());
    assert!(one("--builder-packs", "300,900").is_ok());
    assert!(one("--builder-max-build-cents", "5").is_err());
    assert!(one("--builder-api", "http://api.anthropic.com").is_err());
    let mut a = with_market(BUILDER_FLAGS);
    let last = a.len() - 1;
    a[last] = "bad id";
    assert!(parse(serve_args(&a)).is_err());
}

#[test]
fn builder_setup_needs_only_the_key_file() {
    let m = parse(
        ["builder-setup", "--key-file", "/k"]
            .iter()
            .map(|s| (*s).to_string())
            .collect(),
    );
    assert_eq!(mode_name(&m), "builder-setup");
    assert!(parse(vec!["builder-setup".to_string()]).is_err());
}
