//! Command-line parsing, exercised through the public `parse` entry point.
//!
//! Every flag here is generated by `modules/edge.nix` or `modules/proxy.nix`,
//! so a bad value means a bad NixOS option — and the point of rejecting it at
//! parse time is that the failure names the flag, at boot, instead of
//! surfacing later as "port range exhausted" for a range that was never
//! usable or as a reconciler spinning on a zero-length interval.

use losos_registrar::opts::{parse, Mode};

/// Flags every `serve` invocation needs. Overrides are *prepended* by
/// [`serve_args`], and the parser takes the first occurrence of a flag, so an
/// override wins over the default below.
const SERVE_DEFAULTS: &[&str] = &[
    "--registry",
    "/var/lib/losos-registrar/registry.json",
    "--traefik-dir",
    "/etc/traefik/dynamic",
    "--rathole-config",
    "/etc/rathole/server.toml",
    "--bootstrap-token-file",
    "/var/secrets/bootstrap",
    "--tenants-file",
    "/nix/store/tenants.json",
    "--port-range",
    "50000-50100",
];

fn serve_args(overrides: &[&str]) -> Vec<String> {
    std::iter::once("serve")
        .chain(overrides.iter().copied())
        .chain(SERVE_DEFAULTS.iter().copied())
        .map(str::to_string)
        .collect()
}

fn serve_opts(overrides: &[&str]) -> losos_registrar::opts::ServeOpts {
    match parse(serve_args(overrides)) {
        Ok(Mode::Serve(opts)) => opts,
        Ok(_) => panic!("expected a serve mode"),
        Err(e) => panic!("expected serve args to parse: {e:?}"),
    }
}

#[test]
fn a_full_serve_invocation_parses() {
    let opts = serve_opts(&[]);
    assert_eq!(opts.port_range, (50000, 50100));
    assert_eq!(opts.listen, "127.0.0.1:8443");
    assert_eq!(opts.reconcile_interval, std::time::Duration::from_secs(15));
    assert_eq!(opts.heartbeat_ttl, std::time::Duration::from_secs(120));
}

/// An inverted range makes `alloc_port`'s `(lo..=hi)` sweep empty, so the
/// first appliance to register would be told the range is exhausted with no
/// hint that the range itself was the problem.
#[test]
fn an_inverted_port_range_is_rejected() {
    let result = parse(serve_args(&["--port-range", "50100-50000"]));
    assert!(result.is_err(), "hi < lo must not parse");
}

#[test]
fn a_port_range_starting_at_zero_is_rejected() {
    let result = parse(serve_args(&["--port-range", "0-50100"]));
    assert!(result.is_err(), "port 0 is not bindable");
}

#[test]
fn a_malformed_port_range_is_rejected() {
    for range in ["50000", "50000-", "-50100", "fifty-thousand", ""] {
        let result = parse(serve_args(&["--port-range", range]));
        assert!(result.is_err(), "{range:?} must not parse as a range");
    }
}

#[test]
fn an_equal_low_and_high_range_is_a_single_usable_port() {
    let opts = serve_opts(&["--port-range", "50000-50000"]);
    assert_eq!(opts.port_range, (50000, 50000));
}

/// Zero is never a sane value for any duration this crate parses: a zero
/// reconcile interval is a busy-loop, a zero TTL prunes every tenant on the
/// next tick, and a zero heartbeat interval floods the edge.
#[test]
fn a_zero_duration_is_rejected() {
    for flag in ["--reconcile-interval", "--heartbeat-ttl"] {
        for value in ["0", "0s", "0ms", "0m", "0h"] {
            let result = parse(serve_args(&[flag, value]));
            assert!(result.is_err(), "{flag} {value} must not parse");
        }
    }
}

/// `n * 3600` used to overflow `u64` seconds unchecked — a panic in a debug
/// build, and a silently tiny interval in a release one.
#[test]
fn an_overflowing_duration_is_rejected_not_wrapped() {
    for value in [
        "5124095576030432h",
        "18446744073709551615h",
        "999999999999999999m",
    ] {
        let result = parse(serve_args(&["--heartbeat-ttl", value]));
        assert!(result.is_err(), "{value} must be rejected, not wrapped");
    }
}

#[test]
fn duration_units_are_honoured() {
    use std::time::Duration;
    let cases = [
        ("500ms", Duration::from_millis(500)),
        ("30s", Duration::from_secs(30)),
        ("2m", Duration::from_secs(120)),
        ("1h", Duration::from_secs(3600)),
        ("45", Duration::from_secs(45)),
    ];
    for (text, expected) in cases {
        let opts = serve_opts(&["--heartbeat-ttl", text]);
        assert_eq!(opts.heartbeat_ttl, expected, "parsing {text:?}");
    }
}

#[test]
fn a_missing_required_flag_is_rejected() {
    // No --registry anywhere in the argument list.
    let args: Vec<String> = ["serve", "--port-range", "50000-50100"]
        .into_iter()
        .map(str::to_string)
        .collect();
    assert!(parse(args).is_err());
}

#[test]
fn an_unknown_subcommand_is_rejected() {
    assert!(parse(vec!["frobnicate".to_string()]).is_err());
    assert!(parse(Vec::new()).is_err());
}

#[test]
fn announce_parses_its_own_flags() {
    let args: Vec<String> = [
        "announce",
        "--registrar-url",
        "https://register.losos.cfd",
        "--appliance-id",
        "mattbox",
        "--hostname",
        "mattbox.losos.cfd",
        "--token-file",
        "/var/secrets/losos-proxy-token",
        "--heartbeat-interval",
        "30s",
    ]
    .into_iter()
    .map(str::to_string)
    .collect();
    match parse(args) {
        Ok(Mode::Announce(opts)) => {
            assert_eq!(opts.appliance_id, "mattbox");
            assert_eq!(opts.heartbeat_interval, std::time::Duration::from_secs(30));
        }
        other => panic!("expected an announce mode, got {}", mode_name(&other)),
    }
}

fn mode_name(mode: &miette::Result<Mode>) -> &'static str {
    match mode {
        Ok(Mode::Serve(_)) => "serve",
        Ok(Mode::Announce(_)) => "announce",
        Ok(Mode::Seed(_)) => "seed",
        Err(_) => "error",
    }
}
