# Impermanence: /persist (encrypted, see disko.nix) holds all durable state;
# the root is tmpfs and is rebuilt every boot. Directories listed here are
# bind-mounted from /persist back onto the volatile root.
_:

{
  environment.persistence."/persist" = {
    hideMounts = true;

    directories = [
      "/nix" # the nix store, so packages survive reboot
      "/var" # service state: postgres, redis, nextcloud, forgejo, k3s/rke2, /var/secrets, etc.
      "/etc/ssh" # host keys
      "/etc/keys" # LUKS keyfile source, so auto-upgrade rebuilds can re-bake the initrd
      "/etc/nixos" # the flake source, so auto-upgrade can rebuild without a remote
      # Kubernetes node identity. /var already covers the bulk of both
      # instances' state (/var/lib/rancher/{k3s,rke2}), but NOT this: the
      # agent generates /etc/rancher/node/password on its first join and the
      # server stores a hash of it keyed by node name. On a tmpfs root the
      # file is regenerated every boot, and the server then refuses the
      # rejoin ("Node password rejected"). Without this line the box silently
      # falls out of the mesh on the first reboot after enrolling — and there
      # is no shell to notice it from.
      "/etc/rancher"
      "/home/notshared/data"
      "/home/shared/data"
      # Service state lives under /var/lib/{nextcloud,forgejo} and is covered
      # by the whole-/var bind mount above; so are lososd's
      # /var/lib/losos/state.json, the container images and Kubernetes state
      # under /var/lib/rancher, and the secrets at /var/secrets (the admin
      # token lososd mints, the Nextcloud admin password generated by
      # modules/nextcloud-common.nix, the proxy and mesh tokens).
    ];

    files = [
      "/etc/machine-id"
    ];
  };
}
