# The appliance recovery code — where lososd keeps it, and why there.
#
# What the code is for: the reinstall ISO wipes /persist, and with it every
# scrap of identity this box has. It comes back with a fresh machine-id, a
# fresh /etc/rancher/node/password, and no /var/secrets/losos-proxy-token.
# (`losos-ctl factory-reset` does NOT wipe the disk — it restores the committed
# defaults and rebuilds. The destructive tier is the ISO; see
# backend/src/losos.rs, cmd_factory_reset.)
#
# The appliance half is what this module wires. The edge half — a `recovery`
# map in the registrar's registry.json and a route that trades a code for an
# identity — does not exist, and before building it, read the second section of
# backend/src/recovery.rs: the mesh lockout this code was conceived to prevent
# is ALREADY prevented by /cluster/join's stale-node cleanup, which proves
# identity with the proxy token the box already has. What an edge half would
# actually add is self-service re-issue of that token over an unauthenticated
# internet-reachable route, which is a different feature with a different
# threat model and has not been agreed.
#
# So today this code is minted, stored and displayed, and recovers nothing.
# Nothing consumes it. Do not let the admin UI imply otherwise — and note that
# admin-ui/app/src/screens/wizard/StepRecovery.tsx currently DOES, in the words
# "the only proof that the new box is the old one". That copy and this comment
# have to be settled together.
#
# Why this is a separate module rather than three lines in modules/daemon.nix:
# same reason modules/tls.nix is separate. daemon.nix is about how the control
# plane is *run* — the unit, the bus policy, the sandbox. This is one durable
# secret with a long argument attached to where it lives, and that argument
# wants a file it can be read in.
#
# See backend/src/recovery.rs for the half that mints it, including why the
# read endpoint is gated no harder than every other /api route.
{
  lib,
  config,
  ...
}:

let
  # Same guard as modules/daemon.nix, and it must stay the same. That module
  # defines systemd.services.lososd inside its own `lib.mkIf enabled`; if this
  # one set an environment variable unconditionally it would conjure a
  # lososd.service consisting of nothing but LOSOS_RECOVERY_FILE on a box
  # configured with `losos.backend.package = null`.
  enabled = config.losos.backend.package != null;

  # Hard-coded rather than an option, for two reasons. modules/options.nix is
  # the only sanctioned place to declare a losos.* knob, and there is no knob
  # to declare here: the code is not optional, it has no tuning, and a box
  # whose owner moved the file would be a box whose recovery code the next
  # rebuild cannot find. The same reasoning modules/tls.nix applies to its own
  # `dir`.
  #
  # /var/secrets, not /var/lib/losos: this file is a secret the daemon mints
  # for itself, which is precisely what /var/secrets already holds (the admin
  # token, the Nextcloud bootstrap password, the proxy and mesh tokens).
  # /var/lib/losos is the daemon's *working* state — state.json and the rebuild
  # log — and is wiped by a factory reset, which is the one event this code has
  # to outlive.
  #
  # No tmpfiles rule creates the directory. lososd writes through
  # atomic_write_secret, which creates any missing parent at 0700 before the
  # 0600 file lands, and modules/nextcloud-common.nix already tmpfiles the same
  # path — a second identical rule only earns a "Duplicate line for path"
  # warning from systemd-tmpfiles at every boot.
  #
  # Durability comes from modules/impermanence.nix persisting the whole of
  # /var. Anything outside that list is tmpfs and would hand the owner a new
  # code on every reboot, which is the one thing this feature must never do.
  codeFile = "/var/secrets/losos-recovery-code";
in
{
  config = lib.mkIf enabled {
    # lososd reads this on first start, mints a v4 UUID into it if there is no
    # well-formed code there already, and leaves it alone ever after. NixOS
    # deliberately does not manage the file: it cannot be a store path (the
    # store is world-readable and this is 0600), and a value NixOS generated
    # would be regenerated by the next `nixos-rebuild switch` — invalidating
    # whatever the owner had written down, silently, at 03:00, on a box with no
    # shell to notice it from.
    #
    # Exactly the arrangement losos.admin.tokenFile already uses.
    systemd.services.lososd.environment.LOSOS_RECOVERY_FILE = codeFile;
  };
}
