import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/* One sidebar, generated from the docs/ tree. Each folder's _category_.json
 * carries its label and position; a page's position is its front matter. */
const sidebars: SidebarsConfig = {
  handbook: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
