#!/usr/bin/env bash
# Regenerates src/css/derisk-theme.css, the LosOS desktop's theme as CSS
# variables, from an mcsapi checkout:
#
#   handbook/scripts/derisk-theme.sh /path/to/mcsapi
#
# The values are mcsapi-theme's own export (export::css_variables) of the two
# built-in themes the desktop ships, derisk-light and derisk-dark, so the
# handbook takes the desktop's colours, fonts and radii from the same code
# that themes derisk, GTK, Qt and Android apps, never a hand-copied hex value.
# The script builds a throwaway crate that depends on mcsapi-theme by path;
# the checkout itself is not touched. Then it rewrites the export's two
# `:root` blocks into the handbook's three-state Auto/Light/Dark selectors
# (the same ones tokens.css used) and prefixes every name with `--derisk-`,
# because the export's `--muted` is a fill and the handbook's is text.
set -euo pipefail

mcsapi=${1:?usage: derisk-theme.sh /path/to/mcsapi}
mcsapi=$(cd "$mcsapi" && pwd)
here=$(cd "$(dirname "$0")/.." && pwd)
out=$here/src/css/derisk-theme.css
rev=$(git -C "$mcsapi" rev-parse --short HEAD)

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
mkdir -p "$work/src"
cat >"$work/Cargo.toml" <<TOML
[package]
name = "derisk-theme-css"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
mcsapi-theme = { path = "$mcsapi/crates/mcsapi-theme" }

[workspace]
TOML
cat >"$work/src/main.rs" <<'RS'
fn main() {
    let id = std::env::args().nth(1).expect("theme ID");
    let theme = mcsapi_theme::Theme::builtin(&id).expect("built-in theme");
    print!("{}", mcsapi_theme::export::css_variables(&theme));
}
RS

# The declarations of one theme, without the `:root {` and `}` lines,
# renamed into the --derisk- namespace and indented by $2.
declarations() {
  cargo run --quiet --manifest-path "$work/Cargo.toml" -- "$1" |
    sed -e '1d' -e '$d' -e 's/^  --/  --derisk-/' -e "s/^/$2/"
}
light=$(declarations derisk-light '')
dark=$(declarations derisk-dark '  ')
dark_root=$(declarations derisk-dark '')

cat >"$out" <<CSS
/* The LosOS desktop's theme, generated by scripts/derisk-theme.sh from
 * mcsapi $rev (mcsapi-theme, export::css_variables of derisk-light and
 * derisk-dark). Do not edit: change the desktop theme in mcsapi and run the
 * script again.
 *
 * Bare :root is the light theme. The media arm switches to dark unless the
 * reader picked Light, and the explicit-dark rule comes last at equal
 * specificity so a picked Dark wins the other way. Docusaurus sets
 * data-theme="light|dark" on <html>. */

:root {
$light
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
$dark
  }
}

:root[data-theme="dark"] {
$dark_root
}
CSS
echo "wrote $out from mcsapi $rev"
