#!/usr/bin/env bash
# losos-install — minimal unattended installer for the losos appliance.
#
# This revision pulls the losos flake from the public repository
#   https://codeberg.org/dasmatus/losos.git
# and uses **blkid** (instead of lsblk‑awk) to enumerate candidate disks.
#
# The script still:
#   • Detects fixed, non‑removable disks > 1 GB that are not currently mounted
#   • Generates modules/install-target.nix
#   • Runs disko → nixos‑install
#   • Copies the flake into /persist/etc/nixos and initialises a Git repo
#   • Handles TPM2 or a persistent keyfile
#
# Usage (identical to the original):
#   losos-install                       # auto‑detect drives, keyfile (unattended)
#   losos-install --tpm                 # TPM2 (interactive passphrase at format)
#   losos-install --drives /dev/sdb,/dev/sdc   # override auto‑detection
#   losos-install --no-install          # stop after disko (format+mount)
#   losos-install --disko-script PATH   # use a pre‑built diskoScript instead of `disko --flake`
#   losos-install --emit-target FILE    # only write install-target.nix to FILE and exit
set -euo pipefail

TPM=0
DRIVES_ARG=""
NO_INSTALL=0
DISKO_SCRIPT=""
EMIT_TARGET=""
FLAKE_URL="https://codeberg.org/dasmatus/losos.git"
FLAKE_WORK="${LOSOS_FLAKE_WORK:-/tmp/losos-flake}"
KEYFILE="/etc/keys/persist-keyfile"
TARGET_FILE_REL="modules/install-target.nix"
EMIT_FILE="/tmp/losos-install-target.nix"

usage() {
  cat <<'EOF'
losos-install — minimal unattended losos installer.
  --tpm                  use TPM2 (interactive passphrase at format time)
  --drives A,/dev/b,...  override drive auto‑detection
  --no-install           stop after disko (format+mount), skip nixos‑install
  --disko-script PATH    run a prebuilt diskoScript instead of `disko --flake`
  --emit-target FILE     write install-target.nix to FILE and exit
  -h, --help             show this help
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --tpm) TPM=1; shift ;;
    --drives) DRIVES_ARG="$2"; shift 2 ;;
    --no-install) NO_INSTALL=1; shift ;;
    --disko-script) DISKO_SCRIPT="$2"; shift 2 ;;
    --emit-target) EMIT_TARGET="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "losos-install: unknown flag: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# ── Helper: list block devices currently used by any mount ──────────────────
mounted_disk_names() {
  findmnt -rn -o SOURCE 2>/dev/null |
    sed -E 's#^/dev/##; s#^mapper/##' |
    while read -r src; do
      [ -e "/dev/$src" ] || continue
      blkid -s TYPE -o value "/dev/$src" >/dev/null 2>&1 && \
        lsblk -ndo PKNAME "/dev/$src" 2>/dev/null
    done |
    grep -v '^$' |
    sort -u
}

# ── Detect candidate drives using blkid ───────────────────────────────────────
detect_drives() {
  local skip; skip=$(mounted_disk_names | tr '\n' ' ')
  # List all block devices that blkid can identify as a whole disk (TYPE="disk")
  # Exclude those in the skip list, require size >1 GB, and non‑removable.
  blkid -o export |
    awk -v skip="$skip" '
      BEGIN {
        n = split(skip, s, " ")
        for (i = 1; i <= n; i++) if (s[i] != "") ex[s[i]] = 1
      }
      $1 == "DEVNAME" { dev=$2 }
      $1 == "TYPE" && $2 == "disk" { type=1 }
      $1 == "SIZE" { size=$2 }
      $1 == "RM"   { rm=$2 }
      $0 == "" && type && rm == "0" && size+0 > 1000000000 && !(dev in ex) {
        print dev
        type=rm=size=0
      }
    ' |
    sort
}

# ── Build the drive list (override option takes precedence) ───────────────────
if [ -n "$DRIVES_ARG" ]; then
  IFS=',' read -r -a DRIVES <<< "$DRIVES_ARG"
else
  mapfile -t DRIVES < <(detect_drives)
fi

if [ "${#DRIVES[@]}" -eq 0 ]; then
  echo "losos-install: no candidate fixed disks found." >&2
  echo "  (whole disks, non‑removable, >1 GB, not currently mounted)." >&2
  echo "  Pass --drives /dev/sdb,/dev/sdc to override." >&2
  exit 1
fi

echo "losos-install: target drives: ${DRIVES[*]}"

# ── Render modules/install-target.nix -----------------------------------------
nix_list=$(printf '"%s" ' "${DRIVES[@]}" | sed 's/ *$//')

render_target() {
  cat <<EOF
# Generated by losos-install — do not hand‑edit; re‑run losos-install to
# change the target drives or TPM mode. This file is imported by flake.nix
# only when it exists (builtins.pathExists), so it stays out of the admin
# app's modules/overrides.nix (which losos‑ctl apply rewrites wholesale) and
# out of any published flake. The installer commits it into the local
# /persist/etc/nixos git repo so the default git+file:///etc/nixos
# auto‑upgrade keeps seeing it.
{ ... }:

{
  losos.targetDrives = [ ${nix_list} ];
  losos.tpm.enable = $([ "$TPM" -eq 1 ] && echo true || echo false);
}
EOF
}

if [ -n "$EMIT_TARGET" ]; then
  render_target > "$EMIT_TARGET"
  echo "wrote $EMIT_TARGET"
  exit 0
fi

# ── Keyfile (non‑TPM path only) ───────────────────────────────────────────────
ensure_keyfile() {
  if [ "$TPM" -eq 1 ]; then return; fi
  if [ -e "$KEYFILE" ]; then return; fi
  echo "losos-install: generating $KEYFILE"
  install -d -m 700 "$(dirname "$KEYFILE")"
  dd if=/dev/urandom of="$KEYFILE" bs=512 count=8 status=none
  chmod 600 "$KEYFILE"
}
ensure_keyfile

# ── Test seam: --disko-script -------------------------------------------------
if [ -n "$DISKO_SCRIPT" ]; then
  render_target > "$EMIT_FILE"
  echo "losos-install: running prebuilt diskoScript $DISKO_SCRIPT"
  "$DISKO_SCRIPT"
  echo "losos-install: format+mount complete (test mode, no install)."
  exit 0
fi

# ── Production path ────────────────────────────────────────────────────────
echo "losos-install: cloning losos flake from $FLAKE_URL"
rm -rf "$FLAKE_WORK"
git clone --depth 1 "$FLAKE_URL" "$FLAKE_WORK"

# Populate the target file inside the writable copy
render_target > "$FLAKE_WORK/$TARGET_FILE_REL"

echo "losos-install: disko destroy,format,mount (rootMountPoint=/mnt)"
disko --mode destroy,format,mount --flake "$FLAKE_WORK#install"

if [ "$NO_INSTALL" -eq 1 ]; then
  echo "losos-install: --no-install set; stopping after disko. /mnt is ready."
  exit 0
fi

echo "losos-install: nixos-install --flake $FLAKE_WORK#install"
nixos-install --flake "$FLAKE_WORK#install" --no-root-passwd

# ── Lay the flake at /persist/etc/nixos for auto‑upgrade ─────────────────────
PERSIST_ETC_NIXOS="/mnt/persist/etc/nixos"
PERSIST_KEYS="/mnt/persist/etc/keys"

echo "losos-install: laying flake at $PERSIST_ETC_NIXOS"
install -d "$PERSIST_ETC_NIXOS"
rm -rf "$PERSIST_ETC_NIXOS"
cp -a "$FLAKE_WORK" "$PERSIST_ETC_NIXOS"
chmod -R u+w "$PERSIST_ETC_NIXOS"

( cd "$PERSIST_ETC_NIXOS" \
  && git init -q \
  && git add -A \
  && git -c user.email=losos@local -c user.name=losos-install \
     commit -qm "losos install" )

if [ "$TPM" -eq 0 ]; then
  echo "losos-install: copying keyfile into $PERSIST_KEYS"
  install -d -m 700 "$PERSIST_KEYS"
  cp "$KEYFILE" "$PERSIST_KEYS/persist-keyfile"
  chmod 600 "$PERSIST_KEYS/persist-keyfile"
fi

echo "losos-install: done."
if [ "$TPM" -eq 1 ]; then
  echo "  Boot into the installed system, then enroll TPM2:" >&2
  echo "    systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=0+7 /dev/persist-vg/persist" >&2
fi
echo "  Reboot into the installed system."
